import type {
  TechnicalReviewAlert,
  TechnicalReviewConfigItem,
  TechnicalReviewDocumentReview,
  TechnicalReviewMetric,
  TechnicalReviewMonthlyResult,
  TechnicalReviewOperationalItem,
  TechnicalReviewPlant,
  TechnicalReviewRejectionCase,
  TechnicalReviewTimelineEvent,
} from "@/features/revisiones-tecnicas/types";

export const technicalReviewMetrics: TechnicalReviewMetric[] = [
  {
    label: "Flota total",
    value: "341",
    helper: "Buses con control tecnico activo en 4 terminales",
    tone: "neutral",
  },
  {
    label: "Vigentes",
    value: "287",
    helper: "84.1% de la flota con revision al dia",
    tone: "success",
  },
  {
    label: "Proximas a vencer",
    value: "29",
    helper: "Ventana de advertencia a 21 dias",
    tone: "warning",
  },
  {
    label: "Vencidas",
    value: "7",
    helper: "Requieren accion inmediata del supervisor",
    tone: "danger",
  },
  {
    label: "Pendientes de recepcion",
    value: "12",
    helper: "Envios abiertos sin cierre documental",
    tone: "warning",
  },
  {
    label: "Pendientes de validacion",
    value: "5",
    helper: "Documentos OCR esperando revision humana",
    tone: "neutral",
  },
  {
    label: "Aprobacion primer intento",
    value: "78%",
    helper: "Promedio movil del ultimo trimestre",
    tone: "success",
  },
  {
    label: "Tiempo promedio",
    value: "3.4 dias",
    helper: "Desde salida hasta vigencia confirmada",
    tone: "neutral",
  },
];

export const technicalReviewAlerts: TechnicalReviewAlert[] = [
  {
    id: "rt-alert-1",
    title: "Bus LCHT-82 con vigencia critica",
    description:
      "La revision del bus 4102 vence el 2026-08-12 y aun no existe envio programado.",
    severity: "warning",
    createdAt: "2026-08-06T08:15:00-04:00",
  },
  {
    id: "rt-alert-2",
    title: "Documento con PPU inconsistente",
    description:
      "El OCR detecto LMRP-48, pero el envio abierto corresponde al bus LMRP-43.",
    severity: "danger",
    createdAt: "2026-08-06T09:02:00-04:00",
  },
  {
    id: "rt-alert-3",
    title: "Rechazo sin reparacion iniciada",
    description:
      "El caso de JXWK-17 lleva 2 dias sin responsable asignado para reparacion.",
    severity: "warning",
    createdAt: "2026-08-06T10:40:00-04:00",
  },
];

export const technicalReviewMonthlyResults: TechnicalReviewMonthlyResult[] = [
  { month: "Abr", approved: 38, rejected: 9 },
  { month: "May", approved: 41, rejected: 7 },
  { month: "Jun", approved: 44, rejected: 10 },
  { month: "Jul", approved: 47, rejected: 8 },
  { month: "Ago", approved: 19, rejected: 4 },
];

export const technicalReviewOperationalItems: TechnicalReviewOperationalItem[] = [
  {
    id: "rt-op-1",
    busId: "bus-001",
    ppu: "LCHT-82",
    internalNumber: "4102",
    brand: "Yutong",
    model: "E12 Pro",
    terminal: "El Roble",
    dueDate: "2026-08-12",
    daysRemaining: 6,
    status: "PROXIMO_A_VENCER",
    lastSentAt: "2026-07-18T09:15:00-04:00",
    lastReceivedAt: "2026-07-18T14:40:00-04:00",
    lastResult: "APROBADO",
    rejectionCount: 0,
    attemptCount: 1,
    plant: "Planta Quilicura Norte",
    responsible: "Daniela Paredes",
  },
  {
    id: "rt-op-2",
    busId: "bus-002",
    ppu: "JXWK-17",
    internalNumber: "3098",
    brand: "Volvo",
    model: "B8RLE",
    terminal: "Lo Echevers",
    dueDate: "2026-07-29",
    daysRemaining: -8,
    status: "RECHAZADO",
    lastSentAt: "2026-08-04T08:20:00-04:00",
    lastReceivedAt: "2026-08-04T13:35:00-04:00",
    lastResult: "RECHAZADO",
    rejectionCount: 2,
    attemptCount: 2,
    plant: "Planta Pudahuel RT",
    responsible: "Paula Jorquera",
  },
  {
    id: "rt-op-3",
    busId: "bus-003",
    ppu: "LMRP-43",
    internalNumber: "4120",
    brand: "BYD",
    model: "K9UD",
    terminal: "Colo Colo",
    dueDate: "2026-08-28",
    daysRemaining: 22,
    status: "DOCUMENTO_PENDIENTE_VALIDACION",
    lastSentAt: "2026-08-06T07:45:00-04:00",
    lastReceivedAt: "2026-08-06T12:10:00-04:00",
    lastResult: "PENDIENTE",
    rejectionCount: 0,
    attemptCount: 1,
    plant: "Planta Santiago Centro",
    responsible: "Valentina Mendez",
  },
  {
    id: "rt-op-4",
    busId: "bus-004",
    ppu: "HJFK-55",
    internalNumber: "2814",
    brand: "Mercedes-Benz",
    model: "OF 1721",
    terminal: "El Roble",
    dueDate: "2026-08-03",
    daysRemaining: -3,
    status: "EN_REPARACION",
    lastSentAt: "2026-08-01T08:05:00-04:00",
    lastReceivedAt: "2026-08-01T14:12:00-04:00",
    lastResult: "RECHAZADO",
    rejectionCount: 1,
    attemptCount: 1,
    plant: "Planta Quilicura Norte",
    responsible: "Cristobal Lagos",
  },
];

export const technicalReviewTimeline: TechnicalReviewTimelineEvent[] = [
  {
    id: "rt-timeline-1",
    busId: "bus-002",
    at: "2026-08-04T08:20:00-04:00",
    user: "Daniela Paredes",
    action: "Bus enviado a reinspeccion",
    previousState: "EN_REPARACION",
    nextState: "ENVIADO_REINSPECCION",
    observations: "Salida desde Lo Echevers con conductor interno PRS-220.",
    documents: ["Acta de salida"],
    rejectionReasons: [],
  },
  {
    id: "rt-timeline-2",
    busId: "bus-002",
    at: "2026-08-04T13:35:00-04:00",
    user: "Daniela Paredes",
    action: "Recepcion con resultado rechazado",
    previousState: "ENVIADO_REINSPECCION",
    nextState: "RECHAZADO",
    observations: "Persisten observaciones en sistema de frenos auxiliares.",
    documents: ["Informe de rechazo #81294"],
    rejectionReasons: ["FR-12 Freno auxiliar", "IL-03 Senalizacion lateral"],
  },
  {
    id: "rt-timeline-3",
    busId: "bus-002",
    at: "2026-08-04T15:10:00-04:00",
    user: "Paula Jorquera",
    action: "Documento validado por supervisor",
    previousState: "DOCUMENTO_PENDIENTE_VALIDACION",
    nextState: "RECHAZADO",
    observations: "Se confirmaron folio, planta y motivo principal del rechazo.",
    documents: ["OCR validado"],
    rejectionReasons: ["FR-12 Freno auxiliar"],
  },
  {
    id: "rt-timeline-4",
    busId: "bus-002",
    at: "2026-08-05T08:30:00-04:00",
    user: "Cristobal Lagos",
    action: "Ingreso a reparacion",
    previousState: "RECHAZADO",
    nextState: "EN_REPARACION",
    observations: "Taller asignado con prioridad alta por vencimiento.",
    documents: ["Orden OT-5421"],
    rejectionReasons: ["FR-12 Freno auxiliar"],
  },
];

export const technicalReviewRejections: TechnicalReviewRejectionCase[] = [
  {
    id: "rt-rej-1",
    busId: "bus-002",
    ppu: "JXWK-17",
    internalNumber: "3098",
    terminal: "Lo Echevers",
    plant: "Planta Pudahuel RT",
    status: "EN_REPARACION",
    startedAt: "2026-08-05T08:30:00-04:00",
    estimatedAt: "2026-08-07T18:00:00-04:00",
    finishedAt: null,
    owner: "Cristobal Lagos",
    reasons: ["FR-12 Freno auxiliar", "IL-03 Senalizacion lateral"],
    workDone: "Cambio de latiguillo, ajuste de luces laterales y prueba de ruta.",
  },
  {
    id: "rt-rej-2",
    busId: "bus-004",
    ppu: "HJFK-55",
    internalNumber: "2814",
    terminal: "El Roble",
    plant: "Planta Quilicura Norte",
    status: "LISTO_REINSPECCION",
    startedAt: "2026-08-02T09:00:00-04:00",
    estimatedAt: "2026-08-06T13:00:00-04:00",
    finishedAt: "2026-08-05T17:45:00-04:00",
    owner: "Paula Jorquera",
    reasons: ["EM-09 Emisiones fuera de rango"],
    workDone: "Mantencion preventiva, recambio de filtro y ajuste electronico.",
  },
];

export const technicalReviewPlants: TechnicalReviewPlant[] = [
  {
    id: "plant-1",
    code: "QNR",
    name: "Planta Quilicura Norte",
    commune: "Quilicura",
    region: "Metropolitana",
    active: true,
  },
  {
    id: "plant-2",
    code: "PDR",
    name: "Planta Pudahuel RT",
    commune: "Pudahuel",
    region: "Metropolitana",
    active: true,
  },
  {
    id: "plant-3",
    code: "SSC",
    name: "Planta Santiago Centro",
    commune: "Santiago",
    region: "Metropolitana",
    active: true,
  },
];

export const technicalReviewConfig: TechnicalReviewConfigItem[] = [
  {
    id: "rt-config-1",
    key: "warning_days",
    value: "21",
    description: "Dias previos para mostrar estado proximo a vencer.",
  },
  {
    id: "rt-config-2",
    key: "max_file_size_mb",
    value: "15",
    description: "Tamano maximo permitido para archivos OCR.",
  },
  {
    id: "rt-config-3",
    key: "ocr_min_confidence",
    value: "0.75",
    description: "Umbral minimo para marcar un campo como confiable.",
  },
  {
    id: "rt-config-4",
    key: "allowed_formats",
    value: "pdf,jpg,jpeg,png",
    description: "Lista de formatos aceptados para carga documental.",
  },
];

export const technicalReviewDocumentReview: TechnicalReviewDocumentReview = {
  id: "rt-doc-1",
  busId: "bus-003",
  ppu: "LMRP-43",
  documentType: "Informe de rechazo",
  processingStatus: "REQUIERE_REVISION",
  overallConfidence: 0.82,
  pages: 2,
  warnings: [
    "La PPU detectada no coincide con el bus seleccionado.",
    "El campo kilometraje presenta baja confianza.",
  ],
  fields: [
    {
      id: "field-1",
      name: "PPU",
      ocrValue: "LMRP-48",
      confirmedValue: "LMRP-43",
      confidence: 0.58,
      page: 1,
      corrected: true,
    },
    {
      id: "field-2",
      name: "Folio",
      ocrValue: "81294",
      confirmedValue: "81294",
      confidence: 0.97,
      page: 1,
      corrected: false,
    },
    {
      id: "field-3",
      name: "Planta revisora",
      ocrValue: "Planta Santiago Centro",
      confirmedValue: "Planta Santiago Centro",
      confidence: 0.94,
      page: 1,
      corrected: false,
    },
    {
      id: "field-4",
      name: "Fecha de revision",
      ocrValue: "2026-08-06",
      confirmedValue: "2026-08-06",
      confidence: 0.93,
      page: 1,
      corrected: false,
    },
    {
      id: "field-5",
      name: "Resultado",
      ocrValue: "RECHAZADO",
      confirmedValue: "RECHAZADO",
      confidence: 0.99,
      page: 1,
      corrected: false,
    },
    {
      id: "field-6",
      name: "Kilometraje",
      ocrValue: "18B340",
      confirmedValue: "188340",
      confidence: 0.63,
      page: 2,
      corrected: true,
    },
  ],
};
