import type { AppRole, Permission } from "@/types/domain";

export const permissionsByRole: Record<AppRole, Permission[]> = {
  admin: [
    "dashboard.read",
    "brand.read",
    "notifications.read",
    "reports.read",
    "shifts.read",
    "shifts.manage",
    "tasks.read",
    "tasks.manage",
    "tasks.execute",
    "fleet.read",
    "fleet.manage",
    "personnel.read",
    "personnel.manage",
    "terminals.read",
    "terminals.manage",
    "documents.read",
    "documents.manage",
    "rtg.read",
    "rtg.manage",
    "technical_reviews.read",
    "technical_reviews.manage",
    "technical_reviews.validate",
    "technical_reviews.admin",
    "administration.read",
    "administration.manage",
  ],
  supervisor: [
    "dashboard.read",
    "notifications.read",
    "reports.read",
    "shifts.read",
    "shifts.manage",
    "tasks.read",
    "tasks.manage",
    "fleet.read",
    "personnel.read",
    "terminals.read",
    "documents.read",
    "rtg.read",
    "technical_reviews.read",
    "technical_reviews.manage",
    "technical_reviews.validate",
    "administration.read",
  ],
  inspector: [
    "dashboard.read",
    "notifications.read",
    "tasks.read",
    "tasks.execute",
    "fleet.read",
    "documents.read",
    "technical_reviews.read",
  ],
  inspector_administrativo: [
    "dashboard.read",
    "notifications.read",
    "reports.read",
    "fleet.read",
    "fleet.manage",
    "documents.read",
    "documents.manage",
    "rtg.read",
    "rtg.manage",
    "technical_reviews.read",
    "technical_reviews.manage",
    "technical_reviews.validate",
  ],
  planillero: [
    "dashboard.read",
    "notifications.read",
    "tasks.read",
    "tasks.execute",
    "fleet.read",
  ],
  cleaner: [
    "dashboard.read",
    "notifications.read",
    "tasks.read",
    "tasks.execute",
    "fleet.read",
  ],
  consulta: [
    "dashboard.read",
    "brand.read",
    "notifications.read",
    "reports.read",
    "fleet.read",
    "documents.read",
    "rtg.read",
    "technical_reviews.read",
  ],
};
